openapi: 3.0.0
info:
  title: Orchestrator API
  version: 1.0.0
  description: API specification for the Orchestrator module

paths:
  /generations:
    get:
      summary: List all generations
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Generation'
    post:
      summary: Create a new generation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Generation'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'

  /generations/{id}:
    get:
      summary: Get a generation by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Generation'

  /transactions:
    get:
      summary: List all transactions
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'

  /transactions/{id}:
    get:
      summary: Get a transaction by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
    Generation:
      type: object
      properties:
        id:
          type: integer
          format: int64
        transaction:
          $ref: '#/components/schemas/Transaction'
        image:
          type: string