version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - shared-net

  activemq:
    image: symptoma/activemq:5.18.3
    container_name: activemq
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: "false"
      ACTIVEMQ_USERNAME: myuser
      ACTIVEMQ_PASSWORD: mypwd
      ACTIVEMQ_WEBADMIN_USERNAME: myuserweb
      ACTIVEMQ_WEBADMIN_PASSWORD: mypwd
    ports:
      - "61616:61616"  # Port pour JMS
      - "61613:61613"  # Port pour STOMP
      - "8161:8161"    # Port pour la console web ActiveMQ
    volumes:
      - activemq_data:/var/lib/activemq
      - ./activemq.xml:/opt/activemq/conf/activemq.xml
    restart: always
    networks:
      - shared-net

  img-gen-ln:
    image: registry.gitlab.com/js-asi2/asi2-resources/img-gene-neural-love-api:v1.1
    container_name: img-gen-ln
    environment:
      external.iaimgapi.token: 'v1.412288fb8705ffccfde6dd6c3d88a4cfe2cecf830e09d4e52241cfca2f3128c7'
    ports:
      - "8989:8080"
    restart: always
    networks:
      - shared-net

  ollama-local:
    image: ollama/ollama
    container_name: ollama-local
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    restart: always
    networks:
      - shared-net

  frontend:
    build:
      context: ./atelier-1/frontend
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    restart: always
    networks:
      - shared-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared-net

  api-activemq-log:
    build:
      context: ./atelier-1/api-activemq-log
      dockerfile: Dockerfile
    container_name: api-activemq-log
    depends_on:
      - postgres
      - activemq
    networks:
      - shared-net
    restart: always

  api-backend:
    build:
      context: ./atelier-1/api-backend
      dockerfile: Dockerfile
    container_name: api-backend
    depends_on:
      - postgres
    networks:
      - shared-net
    restart: always

  api-common:
    build:
      context: ./atelier-1/api-common
      dockerfile: Dockerfile
    container_name: api-common
    networks:
      - shared-net
    restart: always

  api-gateway:
    build:
      context: ./atelier-1/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - api-common
    networks:
      - shared-net
    restart: always

  api-generation-image-microservice:
    build:
      context: ./atelier-1/api-generation-image-microservice
      dockerfile: Dockerfile
    container_name: api-generation-image-microservice
    depends_on:
      - api-common
    networks:
      - shared-net
    restart: always

  api-generation-property-microservice:
    build:
      context: ./atelier-1/api-generation-property-microservice
      dockerfile: Dockerfile
    container_name: api-generation-property-microservice
    depends_on:
      - api-common
    networks:
      - shared-net
    restart: always

  api-generation-text-microservice:
    build:
      context: ./atelier-1/api-generation-text-microservice
      dockerfile: Dockerfile
    container_name: api-generation-text-microservice
    depends_on:
      - api-common
    networks:
      - shared-net
    restart: always

  api-orchestrator-microservice:
    build:
      context: ./atelier-1/api-orchestrator-microservice
      dockerfile: Dockerfile
    container_name: api-orchestrator-microservice
    depends_on:
      - api-common
    networks:
      - shared-net
    restart: always

volumes:
  ollama:
  postgres_data:
  activemq_data:

networks:
  shared-net:
    driver: bridge
